default_branch: main

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme@pcmultlectwithmasterormain

kramdown:
  parse_block_html: false

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include:
  - _pages

timezone: America/Los_Angeles

url: https://ucsb-cs16.github.io
baseurl: "/w22"
github_url: https://github.com/ucsb-cs16/w22

title: "UCSB CS16"
course: "CS16"
qtr: "W22"
quarter: "Winter 2022"

ta_names: "TBA"
la_names: "TBA"
la_apprentice_names: "TBA"
lab_times: "W: 1p,2p,3p,4p"
instructor: "Zeyu Deng"
lecture_times: "TR - 3:30p-4:45p"
lecture_location: "Embarcadero Hall"
github_org: ucsb-cs16-w22

gauchospace: https://gauchospace.ucsb.edu
campuswire: https://campuswire.com

start_week: 1
start_date: 2022-01-02 
num_weeks: 10
extra_exam_week: true
lecture_days_of_week: TR

instructor_url: https://ucsb-cs16.github.io/instructor

cal_dates: >
  [                                                                            
    {"label":"W22 1st day of instruction", "date":"2022-01-03" },
    {"label":"MLK Day", "date":"2022-01-17" },
    {"label":"President's Day", "date":"2022-02-21" },
    {"label":"W22 instruction ends", "date":"2022-03-11" },
    {"label":"W21 finals start", "date":"2022-03-12" },
    {"label":"W21 CS16 MIDTERM (2pm-3:15pm)", "date":"2022-02-03" },                      
    {"label":"W21 CS16 FINAL (4pm-7pm)", "date":"2022-03-17" },                      
    {"label":"W21 finals end", "date":"2022-03-10" },                          
    {"label":"W21 qtr ends", "date":"2022-12-10" }                              
  ]


collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
